// Code generated by protoc-gen-go.
// source: protobuf/task/task.proto
// DO NOT EDIT!

/*
Package task is a generated protocol buffer package.

It is generated from these files:
	protobuf/task/task.proto

It has these top-level messages:
	TaskInbound
	TaskOutbound
*/
package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskInbound struct {
	TaskId uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (m *TaskInbound) Reset()                    { *m = TaskInbound{} }
func (m *TaskInbound) String() string            { return proto.CompactTextString(m) }
func (*TaskInbound) ProtoMessage()               {}
func (*TaskInbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TaskInbound) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type TaskOutbound struct {
	TaskId uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *TaskOutbound) Reset()                    { *m = TaskOutbound{} }
func (m *TaskOutbound) String() string            { return proto.CompactTextString(m) }
func (*TaskOutbound) ProtoMessage()               {}
func (*TaskOutbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TaskOutbound) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskOutbound) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskInbound)(nil), "messages.TaskInbound")
	proto.RegisterType((*TaskOutbound)(nil), "messages.TaskOutbound")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	GetTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error) {
	out := new(TaskOutbound)
	err := grpc.Invoke(ctx, "/messages.TaskService/GetTaskService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	GetTaskService(context.Context, *TaskInbound) (*TaskOutbound, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetTaskService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.TaskService/GetTaskService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskService(ctx, req.(*TaskInbound))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskService",
			Handler:    _TaskService_GetTaskService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/task/task.proto",
}

func init() { proto.RegisterFile("protobuf/task/task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x49, 0x2c, 0xce, 0x06, 0x13, 0x7a, 0x60, 0x21, 0x21, 0x8e,
	0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0xd4, 0x62, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54,
	0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62,
	0x88, 0x3a, 0x25, 0x35, 0x2e, 0xee, 0x90, 0xc4, 0xe2, 0x6c, 0xcf, 0xbc, 0xa4, 0xfc, 0xd2, 0xbc,
	0x14, 0x21, 0x71, 0x2e, 0x76, 0x90, 0x21, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc,
	0x41, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x92, 0x2d, 0x17, 0x0f, 0x48, 0x9d, 0x7f, 0x69, 0x09, 0x7e,
	0x85, 0x42, 0x22, 0x5c, 0xac, 0x25, 0x99, 0x25, 0x39, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x10, 0x8e, 0x51, 0x02, 0xc4, 0x9a, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0xa1, 0x40,
	0x2e, 0x3e, 0xf7, 0xd4, 0x12, 0x64, 0x11, 0x51, 0x3d, 0x98, 0x83, 0xf5, 0x90, 0xdc, 0x23, 0x25,
	0x86, 0x2a, 0x0c, 0xb3, 0x5e, 0x49, 0xa0, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x5c, 0x42, 0x1c, 0xfa,
	0x65, 0x86, 0x60, 0x6f, 0x3b, 0x99, 0x70, 0x49, 0x24, 0x16, 0x14, 0xe8, 0xa5, 0x17, 0x15, 0x24,
	0xeb, 0x15, 0xa7, 0x16, 0x95, 0xa5, 0x16, 0xe9, 0xa5, 0xa7, 0xe6, 0xe9, 0x81, 0xe5, 0x04, 0x90,
	0x6c, 0x0a, 0x00, 0x79, 0x3b, 0x80, 0x31, 0x8a, 0x05, 0x24, 0x93, 0xc4, 0x06, 0x0e, 0x05, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xe7, 0x8b, 0x15, 0x49, 0x01, 0x00, 0x00,
}
