// Code generated by protoc-gen-go.
// source: protobuf/task/task.proto
// DO NOT EDIT!

/*
Package task is a generated protocol buffer package.

It is generated from these files:
	protobuf/task/task.proto

It has these top-level messages:
	TaskInbound
	TaskListInbound
	CreateTaskInbound
	UpdateTaskInbound
	TaskOutbound
*/
package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskInbound struct {
	TaskId uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (m *TaskInbound) Reset()                    { *m = TaskInbound{} }
func (m *TaskInbound) String() string            { return proto.CompactTextString(m) }
func (*TaskInbound) ProtoMessage()               {}
func (*TaskInbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TaskInbound) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type TaskListInbound struct {
	Page uint32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
}

func (m *TaskListInbound) Reset()                    { *m = TaskListInbound{} }
func (m *TaskListInbound) String() string            { return proto.CompactTextString(m) }
func (*TaskListInbound) ProtoMessage()               {}
func (*TaskListInbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TaskListInbound) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CreateTaskInbound struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
}

func (m *CreateTaskInbound) Reset()                    { *m = CreateTaskInbound{} }
func (m *CreateTaskInbound) String() string            { return proto.CompactTextString(m) }
func (*CreateTaskInbound) ProtoMessage()               {}
func (*CreateTaskInbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateTaskInbound) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateTaskInbound struct {
	TaskId uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *UpdateTaskInbound) Reset()                    { *m = UpdateTaskInbound{} }
func (m *UpdateTaskInbound) String() string            { return proto.CompactTextString(m) }
func (*UpdateTaskInbound) ProtoMessage()               {}
func (*UpdateTaskInbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateTaskInbound) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *UpdateTaskInbound) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TaskOutbound struct {
	TaskId     uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	FinishedAt string `protobuf:"bytes,3,opt,name=finishedAt" json:"finishedAt,omitempty"`
	CreatedAt  string `protobuf:"bytes,4,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt  string `protobuf:"bytes,5,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (m *TaskOutbound) Reset()                    { *m = TaskOutbound{} }
func (m *TaskOutbound) String() string            { return proto.CompactTextString(m) }
func (*TaskOutbound) ProtoMessage()               {}
func (*TaskOutbound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TaskOutbound) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskOutbound) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaskOutbound) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

func (m *TaskOutbound) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TaskOutbound) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskInbound)(nil), "messages.TaskInbound")
	proto.RegisterType((*TaskListInbound)(nil), "messages.TaskListInbound")
	proto.RegisterType((*CreateTaskInbound)(nil), "messages.CreateTaskInbound")
	proto.RegisterType((*UpdateTaskInbound)(nil), "messages.UpdateTaskInbound")
	proto.RegisterType((*TaskOutbound)(nil), "messages.TaskOutbound")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	GetTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error)
	GetTaskListService(ctx context.Context, in *TaskListInbound, opts ...grpc.CallOption) (TaskService_GetTaskListServiceClient, error)
	CreateTaskService(ctx context.Context, in *CreateTaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error)
	UpdateTaskService(ctx context.Context, in *UpdateTaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error)
	DeleteTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error)
	FinishTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error) {
	out := new(TaskOutbound)
	err := grpc.Invoke(ctx, "/messages.TaskService/GetTaskService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskListService(ctx context.Context, in *TaskListInbound, opts ...grpc.CallOption) (TaskService_GetTaskListServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TaskService_serviceDesc.Streams[0], c.cc, "/messages.TaskService/GetTaskListService", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceGetTaskListServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskService_GetTaskListServiceClient interface {
	Recv() (*TaskOutbound, error)
	grpc.ClientStream
}

type taskServiceGetTaskListServiceClient struct {
	grpc.ClientStream
}

func (x *taskServiceGetTaskListServiceClient) Recv() (*TaskOutbound, error) {
	m := new(TaskOutbound)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskServiceClient) CreateTaskService(ctx context.Context, in *CreateTaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error) {
	out := new(TaskOutbound)
	err := grpc.Invoke(ctx, "/messages.TaskService/CreateTaskService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTaskService(ctx context.Context, in *UpdateTaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error) {
	out := new(TaskOutbound)
	err := grpc.Invoke(ctx, "/messages.TaskService/UpdateTaskService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error) {
	out := new(TaskOutbound)
	err := grpc.Invoke(ctx, "/messages.TaskService/DeleteTaskService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FinishTaskService(ctx context.Context, in *TaskInbound, opts ...grpc.CallOption) (*TaskOutbound, error) {
	out := new(TaskOutbound)
	err := grpc.Invoke(ctx, "/messages.TaskService/FinishTaskService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	GetTaskService(context.Context, *TaskInbound) (*TaskOutbound, error)
	GetTaskListService(*TaskListInbound, TaskService_GetTaskListServiceServer) error
	CreateTaskService(context.Context, *CreateTaskInbound) (*TaskOutbound, error)
	UpdateTaskService(context.Context, *UpdateTaskInbound) (*TaskOutbound, error)
	DeleteTaskService(context.Context, *TaskInbound) (*TaskOutbound, error)
	FinishTaskService(context.Context, *TaskInbound) (*TaskOutbound, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetTaskService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.TaskService/GetTaskService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskService(ctx, req.(*TaskInbound))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskListService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskListInbound)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskServiceServer).GetTaskListService(m, &taskServiceGetTaskListServiceServer{stream})
}

type TaskService_GetTaskListServiceServer interface {
	Send(*TaskOutbound) error
	grpc.ServerStream
}

type taskServiceGetTaskListServiceServer struct {
	grpc.ServerStream
}

func (x *taskServiceGetTaskListServiceServer) Send(m *TaskOutbound) error {
	return x.ServerStream.SendMsg(m)
}

func _TaskService_CreateTaskService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTaskService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.TaskService/CreateTaskService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTaskService(ctx, req.(*CreateTaskInbound))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTaskService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTaskService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.TaskService/UpdateTaskService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTaskService(ctx, req.(*UpdateTaskInbound))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTaskService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTaskService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.TaskService/DeleteTaskService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTaskService(ctx, req.(*TaskInbound))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FinishTaskService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FinishTaskService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.TaskService/FinishTaskService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FinishTaskService(ctx, req.(*TaskInbound))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskService",
			Handler:    _TaskService_GetTaskService_Handler,
		},
		{
			MethodName: "CreateTaskService",
			Handler:    _TaskService_CreateTaskService_Handler,
		},
		{
			MethodName: "UpdateTaskService",
			Handler:    _TaskService_UpdateTaskService_Handler,
		},
		{
			MethodName: "DeleteTaskService",
			Handler:    _TaskService_DeleteTaskService_Handler,
		},
		{
			MethodName: "FinishTaskService",
			Handler:    _TaskService_FinishTaskService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTaskListService",
			Handler:       _TaskService_GetTaskListService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/task/task.proto",
}

func init() { proto.RegisterFile("protobuf/task/task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x93, 0x6f, 0x4e, 0xdb, 0x30,
	0x18, 0xc6, 0x95, 0x2e, 0xed, 0xda, 0xb7, 0xdb, 0xda, 0x58, 0xdb, 0x9a, 0x65, 0xd5, 0x34, 0x45,
	0xda, 0xb4, 0xf1, 0x21, 0xe1, 0xdf, 0x05, 0x28, 0x08, 0x54, 0x09, 0x89, 0x52, 0xca, 0x97, 0x82,
	0x84, 0xdc, 0xc6, 0x0d, 0x56, 0x4b, 0x12, 0xc5, 0x4e, 0x0f, 0xc0, 0x15, 0xf8, 0xc4, 0x11, 0x38,
	0x0f, 0x57, 0xe0, 0x20, 0xc8, 0x4e, 0x43, 0x5c, 0x4a, 0x55, 0xa9, 0x7c, 0x89, 0xe2, 0xf7, 0x79,
	0xfc, 0xf3, 0x9f, 0xe7, 0x35, 0x98, 0x51, 0x1c, 0xf2, 0x70, 0x90, 0x8c, 0x5c, 0x8e, 0xd9, 0x58,
	0x7e, 0x1c, 0x59, 0x42, 0xe5, 0x1b, 0xc2, 0x18, 0xf6, 0x09, 0xb3, 0x9a, 0x7e, 0x18, 0xfa, 0x13,
	0xe2, 0xe2, 0x88, 0xba, 0x38, 0x08, 0x42, 0x8e, 0x39, 0x0d, 0x03, 0x96, 0xfa, 0xec, 0xbf, 0x50,
	0xed, 0x61, 0x36, 0x6e, 0x07, 0x83, 0x30, 0x09, 0x3c, 0xd4, 0x80, 0x8f, 0x02, 0x72, 0x45, 0x3d,
	0x53, 0xfb, 0xad, 0xfd, 0xfb, 0xdc, 0x2d, 0x89, 0x61, 0xdb, 0xb3, 0xff, 0x40, 0x4d, 0xf8, 0x8e,
	0x29, 0xe3, 0x99, 0x17, 0x81, 0x1e, 0x61, 0x9f, 0xcc, 0x8c, 0xf2, 0xdf, 0xfe, 0x0f, 0xc6, 0x7e,
	0x4c, 0x30, 0x27, 0x2a, 0xf4, 0x2b, 0x14, 0x39, 0xe5, 0x93, 0xd4, 0x59, 0xe9, 0xa6, 0x03, 0xbb,
	0x05, 0xc6, 0x79, 0xe4, 0xbd, 0xb2, 0x2e, 0x5b, 0x3f, 0x67, 0x14, 0x54, 0xc6, 0xbd, 0x06, 0x9f,
	0xc4, 0xf4, 0x93, 0x84, 0xaf, 0x33, 0x1f, 0xfd, 0x02, 0x18, 0xd1, 0x80, 0xb2, 0x6b, 0xe2, 0xed,
	0x71, 0xf3, 0x83, 0x94, 0x94, 0x0a, 0x6a, 0x42, 0x65, 0x28, 0x8f, 0x23, 0x64, 0x5d, 0xca, 0x79,
	0x41, 0xa8, 0x89, 0x3c, 0x81, 0x50, 0x8b, 0xa9, 0xfa, 0x52, 0xd8, 0x7e, 0xd0, 0xd3, 0xab, 0x3d,
	0x23, 0xf1, 0x94, 0x0e, 0x09, 0x3a, 0x85, 0x2f, 0x47, 0x84, 0xab, 0x95, 0x6f, 0x4e, 0x16, 0x92,
	0xa3, 0xdc, 0x81, 0xf5, 0x7d, 0xbe, 0x9c, 0x9d, 0xcd, 0xae, 0xdf, 0x3e, 0x3e, 0xdd, 0x15, 0x00,
	0x95, 0xdd, 0xe9, 0x96, 0x8c, 0x1a, 0x5d, 0x02, 0x9a, 0x21, 0x45, 0x2e, 0x19, 0xf6, 0xc7, 0xfc,
	0x7c, 0x25, 0xb2, 0xa5, 0x68, 0x43, 0xa2, 0xab, 0xa8, 0x92, 0xa1, 0xd9, 0xa6, 0x86, 0xfa, 0x6a,
	0x96, 0x19, 0xfc, 0x67, 0x4e, 0x58, 0x08, 0x7a, 0xd5, 0xce, 0xed, 0x7c, 0xe7, 0x7d, 0x35, 0xfc,
	0x37, 0xd8, 0x0b, 0x9d, 0xb1, 0x8a, 0x6d, 0xe5, 0xec, 0x1e, 0x18, 0x07, 0x64, 0x42, 0xe6, 0xd9,
	0xeb, 0xdd, 0xf5, 0x46, 0x4e, 0xbd, 0x00, 0xe3, 0x50, 0x36, 0xc6, 0x3b, 0xa8, 0x0d, 0x49, 0x35,
	0xac, 0x5a, 0x46, 0x75, 0xd3, 0x5e, 0x6b, 0xed, 0x82, 0x89, 0xa3, 0xc8, 0xf1, 0xe3, 0x68, 0xe8,
	0x30, 0x12, 0x4f, 0x49, 0xec, 0xf8, 0x24, 0x70, 0x84, 0xa5, 0x55, 0x57, 0x16, 0xec, 0x88, 0x37,
	0xdb, 0xd1, 0xfa, 0xba, 0x50, 0x06, 0x25, 0xf9, 0x84, 0x77, 0x9e, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x08, 0x8d, 0x7d, 0x58, 0x06, 0x04, 0x00, 0x00,
}
